---
- name: Configure servers Scayle
  hosts: all
  become: true

  roles: 
  - disable-automatic-updates
  - install-openvm-tools
  - modify-root-prompt
  - disable-kernel-update

  tasks:
  - include_tasks: tasks/change-dateZone.yaml
  - include_tasks: tasks/modify-motd.yaml
