---
- name: Configure servers Scayle
  hosts: all
  become: true
  # Para login SSH mediante contraseña, hace falta el paquete sshpass
  #vars:
  # ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  # ansible_ssh_user: sysops
  # ansible_ssh_pass: sysops

  roles: 
  - disable-automatic-updates
  - install-openvm-tools
  - modify-root-prompt
  - disable-kernel-update
  - Create-user-with-password
  #- change-netplan-config #Comentado porque reinicia la conexion
  

  tasks:
  - include_tasks: tasks/change-dateZone.yaml
  - include_tasks: tasks/modify-motd.yaml
