---
- name: Install NTP packet
  ansible.builtin.apt:
    name: ntp
    state: present

- name: Install ntpdate packet
  ansible.builtin.apt:
    name: ntpdate
    state: present

# Se para antes de sincronizar la hora
- name: Stop NTP service
  ansible.builtin.service:
    name: ntp
    state: stopped

- name: Configure NTP file
  ansible.builtin.lineinfile:
    path: /etc/ntpsec/ntp.conf
    regexp: "^server"
    line: "server {{ servidor_ntp }}"
    state: present

- name: Sincronize current time with NTP server
  ansible.builtin.command: ntpdate {{ servidor_ntp }}

# Se inicia el servicio tras la configuración
- name: Start NTP service
  ansible.builtin.service:
    name: ntp
    state: started
