---
- name: Set sysctl config
  ansible.builtin.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: "net.ipv4.ip_forward", value: 0 }
    - { name: "net.ipv4.conf.default.accept_source_route", value: 0 }
    - { name: "ketnel.sysrq", value: 0 }
    - { name: "net.ipv4.tcp_syncookies", value: 1 }
    - { name: "net.ipv4.tcp_synack_retries", value: 5 }
    - { name: "net.ipv4.conf.default.rp_filter", value: 1 }
    - { name: "net.ipv4.conf.all.rp_filter", value: 1 }
    - { name: "net.ipv4.tcp_rmem", value: "4096 87380 8388608" }
    - { name: "net.ipv4.tcp_wmem", value: "4096 87380 8388608" }
    - { name: "fs.file-max", value: 65535 }
    - { name: "kernel.pid_max", value: 65536 }
    - { name: "net.ipv4.ip_local_port_range", value: "2000 65000" }
